<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Assignment extends Model
{
    protected $guarded = [];

    public function getRouteKeyName()
    {
        return 'id'; // TODO: Change the autogenerated stub
    }

    public function course () {
        return $this->belongsTo(Course::class, 'course_id');
    }
}
