<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{

//    public function getRouteKeyName()
//    {
//        return 'slug'; // TODO: Change the autogenerated stub
//    }

    protected $guarded = [];
}
