<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    protected $guarded = [];

    public function getRouteKeyName()
    {
        return 'id'; // TODO: Change the autogenerated stub
    }

    public function assignments () {
        return $this->hasMany(Assignment::class);
    }

}
